"use client";

import { useState } from "react";
import Link from "next/link";
import Image from "next/image";

const sequence = [
  ["01", "New device", "03:12:08", "device_81ab"],
  ["02", "Password reset", "03:13:01", "53 seconds later"],
  ["03", "New beneficiary", "03:13:19", "first seen"],
  ["04", "High-value transfer", "03:14:02", "₦650,000 · 18.4× median"],
];

export default function LandingPage() {
  const [menuOpen, setMenuOpen] = useState(false);
  const closeMenu = () => setMenuOpen(false);

  return <main className="landing"><nav className={`landing-nav ${menuOpen ? "menu-open" : ""}`}><Link href="/" className="landing-brand" onClick={closeMenu}><Image src="/Nche.png" width={104} height={36} alt="Nche" priority /></Link><div className="landing-links"><a href="#why" onClick={closeMenu}>Why Nche</a><a href="#command" onClick={closeMenu}>Nche Command</a><a href="#how" onClick={closeMenu}>How it works</a></div><div className="landing-actions"><Link href="/demo" className="nav-quiet" onClick={closeMenu}>Run the demo</Link><Link href="/login?next=%2Foverview" className="nav-cta" onClick={closeMenu}>Open Command <span>↗</span></Link></div><button className="landing-menu" aria-label={menuOpen ? "Close menu" : "Open menu"} aria-expanded={menuOpen} aria-controls="landing-mobile-menu" onClick={() => setMenuOpen((value) => !value)}>{menuOpen ? "×" : "☰"}</button><div id="landing-mobile-menu" className={`landing-mobile-menu ${menuOpen ? "is-open" : ""}`}><div className="landing-mobile-links"><a href="#why" onClick={closeMenu}>Why Nche <span>↓</span></a><a href="#command" onClick={closeMenu}>Nche Command <span>↓</span></a><a href="#how" onClick={closeMenu}>How it works <span>↓</span></a><Link href="/demo" onClick={closeMenu}>Run the demo <span>↗</span></Link><Link href="/login?next=%2Foverview" className="nav-cta" onClick={closeMenu}>Open Command <span>↗</span></Link></div></div></nav>
    <section className="landing-hero"><div className="hero-kicker"><span className="kicker-dot" />Account-takeover intelligence <span className="kicker-line" /> Built for Nigeria</div><h1>The password is correct.<br /><span className="headline-highlight">The customer is not.</span></h1><p className="hero-lead">Nche helps financial institutions understand what happens after authentication—before an unusual sequence becomes an irreversible transfer.</p><div className="hero-actions"><Link href="/login?next=%2Foverview" className="hero-cta">Explore Nche Command <span>↗</span></Link><Link href="/demo" className="hero-secondary">See the attack demo <span>→</span></Link></div><div className="hero-trust"><span>Decision support for</span><span className="trust-rule" /><span>banks</span><span>fintechs</span><span>PSBs</span><span>MMOs</span></div></section>
    <section id="command" className="product-preview"><div className="preview-window"><div className="preview-chrome"><div className="window-dots"><i /><i /><i /></div><span>Nche Command <b>·</b> Overview</span><span className="preview-live"><i /> Live</span></div><div className="preview-body"><aside className="preview-sidebar"><strong><span className="mini-mark">N</span> Nche</strong><small>COMMAND</small><div className="preview-nav"><b>Overview</b><span>Alerts <em>7</em></span><span>Investigations</span><span>Beneficiaries</span><span>Evaluation</span></div><div className="preview-side-footer">● Monitoring live</div></aside><div className="preview-content"><div className="preview-heading"><div><span>NCHE COMMAND / OVERVIEW</span><h3>Good morning, analyst.</h3></div><button>Last 24 hours⌄</button></div><div className="preview-metrics"><div><span>Open investigations</span><strong>12</strong><small>3 critical · 4 high</small></div><div><span>Decisions today</span><strong>4,821</strong><small className="cyan-text">↑ 8.2% vs yesterday</small></div><div><span>Critical alerts</span><strong className="red-text">7</strong><small>Needs attention</small></div></div><div className="preview-panels"><div className="preview-alert"><div className="preview-alert-top"><span>Latest critical case</span><b>BLOCK</b></div><h4>Account takeover sequence detected</h4><p>A new device login was followed by a password reset and first-time beneficiary within 64 seconds.</p><div className="preview-sequence">{sequence.map(([id, name, time, detail]) => <div key={id}><span className="seq-id">{id}</span><span className="seq-dot" /><span className="seq-name">{name}</span><small>{time}<br />{detail}</small></div>)}</div><div className="preview-alert-foot"><strong>Risk score <b>96</b></strong><span>customer_7fd9a2</span><span>Open investigation →</span></div></div><div className="preview-chart"><span>Decision distribution</span><strong>Today <small>4,821 total</small></strong><div className="bars"><i style={{ height: "78%" }} /><i style={{ height: "63%" }} /><i style={{ height: "91%" }} /><i style={{ height: "52%" }} /><i style={{ height: "68%" }} /><i style={{ height: "84%" }} /><i style={{ height: "47%" }} /><i style={{ height: "76%" }} /></div><div className="chart-legend"><span><i className="allow-bg" />Allow 87.1%</span><span><i className="block-bg" />Block 0.6%</span></div></div></div></div></div></div><p className="preview-caption"><span>01</span> A quiet view of the signals that change a decision.</p></section>
    <section id="why" className="landing-section split-section"><div className="section-copy"><p className="eyebrow">The problem after login</p><h2>Authentication succeeded <span>≠</span> ownership is certain.</h2><p>Fraudsters do not need to break the password when social engineering gives them the right one. Nche watches the next few minutes—the device, the reset, the recipient, the amount—and gives the institution a defensible next step.</p><Link href="/demo" className="text-link">Walk through a takeover <span>→</span></Link></div><div className="signal-card"><div className="signal-card-head"><span>SEQUENCE / CUSTOMER_7FD9A2</span><span className="signal-live"><i /> LIVE</span></div><div className="signal-card-main"><div className="signal-score"><strong>96</strong><span>critical risk</span></div><div className="signal-copy"><b>Account takeover sequence</b><p>Four signals that are ordinary alone. Together, they are not.</p></div></div><div className="signal-foot"><span>Elapsed time</span><strong>01m 54s</strong><span>Historical occurrences</span><strong>0</strong></div></div></section>
    <section id="how" className="landing-section principles"><div className="section-heading"><p className="eyebrow">What Nche brings together</p><h2>Behaviour is a sequence, not a single event.</h2></div><div className="principle-grid"><article><span>01</span><h3>Cross-channel context</h3><p>Mobile, web, and USSD activity normalized into one customer timeline.</p></article><article><span>02</span><h3>Beneficiary intelligence</h3><p>Sender behaviour meets recipient novelty, velocity, and mule-risk signals.</p></article><article><span>03</span><h3>Explainable decisions</h3><p>Every recommendation carries the evidence object an analyst can reconstruct.</p></article></div></section>
    <section className="landing-bottom"><div><p className="eyebrow">Ready for the sensitive action</p><h2>Make the next decision<br /><span>legible.</span></h2></div><Link href="/login?next=%2Foverview" className="hero-cta">Open Nche Command <span>↗</span></Link></section><footer className="landing-footer"><span>© 2026 Nche Risk Intelligence</span><span>Decision support. Institution-owned authority.</span><span>Built for the Nigerian digital economy.</span></footer>
  </main>;
}